from pathlib import Path
import hashlib,re,subprocess
root=Path.cwd().resolve()
css=root/'assets/control-sizing.css'
header='''/* Shared control geometry. Change only --control-size to resize the site's
   round controls and matching capsules. Loaded last in <head>, before paint.
   Count badges, checkboxes, text typography and engagement tabs are not buttons
   in this size family; their existing appearance and behavior stay untouched. */
:root {
  --control-size: 2.9rem;
  --control-capsule-gap: .5rem;
  --control-inner-size: calc(var(--control-size) - 2px);
  --header-control-size: var(--control-size);
  --reader-control-size: var(--control-size);
  /* Tags keep the earlier compact shared geometry by default. */
  --tag-capsule-size: calc(var(--control-size) * .8);
  --tag-capsule-inner-size: calc(var(--tag-capsule-size) - 2px);
  --tag-capsule-radius: .45rem;
  --tag-capsule-padding-block: .15rem;
  --tag-capsule-padding-inline: .55rem;
  --tag-capsule-count-inset: .3rem;
  --tag-capsule-content-gap: .35rem;
  --tag-capsule-gap: .3rem;
}

/* The homepage/main tag menu alone uses the tighter geometry requested here.
   Directory, post, search and all other tag families inherit the shared values
   above, so this adjustment cannot leak into those components. */
:root .home-main > .subject-nav {
  --tag-capsule-size: calc(var(--control-size) * .675);
  --tag-capsule-inner-size: calc(var(--tag-capsule-size) - 2px);
  --tag-capsule-radius: .4rem;
  --tag-capsule-padding-block: .05rem;
  --tag-capsule-padding-inline: .4rem;
  --tag-capsule-count-inset: .2rem;
  --tag-capsule-content-gap: .25rem;
  --tag-capsule-gap: .25rem;
}

'''
text=css.read_text();text=header+text[text.index('/* Retain the component names'):];css.write_text(text)
assert subprocess.check_output(['git','hash-object',str(css)],text=True).strip()=='539981ab6b117ea42e2d8736523edd9a1d7b5ea1'
css=root/'assets/post-layout.css';text=css.read_text()
old='''/* One placement rule owns both kinds of attached controls. Keep the existing
   physical end anchor because post-engagement itself deliberately uses LTR. */'''
new='''/* One placement rule owns both kinds of attached controls. Their top border
   occupies the same row as the host frame's bottom border, so the attachment
   reads as one continuous border rather than two separated lines. Keep the
   existing physical end anchor because post-engagement itself deliberately uses LTR. */'''
assert text.count(old)==1
text=text.replace(old,new)
anchor=':root :is(.post-card > .post-engagement, .comment-box > .comment-engagement-dock) {'
start=text.index(anchor);end=text.index('}',start)
part=text[start:end];assert part.count('inset-block-start: calc(100% + 1px);')==1
text=text[:start]+part.replace('inset-block-start: calc(100% + 1px);','inset-block-start: 100%;')+text[end:]
start=text.index('/* Posts and comments use the same engagement segments');end=text.index('\n/* Quiet controls',start)
part=text[start:end].encode()
assert hashlib.sha1(b'blob '+str(len(part)).encode()+b'\0'+part).hexdigest()=='4f8e28e51640846ccb37f776db0f06e184f4e4df'
css.write_text(text)
versions={name:hashlib.sha256((root/'assets'/name).read_bytes()).hexdigest()[:12] for name in ['control-sizing.css','post-layout.css','appearance.js']}
for path in root.rglob('*.html'):
 text=path.read_text()
 for name,version in versions.items():text=re.sub(r'(assets/'+re.escape(name)+r'\?v=)[a-f0-9]{12}',lambda m:m[1]+version,text)
 path.write_text(text)
latest='8a246ce6582c8c60c6bcf87e5ded15b6f0a2eb02'
assert subprocess.check_output(['git','diff','--name-only','0c898b90955589edc4cab5c86162d18942061c85',latest],text=True).splitlines()==['assets/control-sizing.css','assets/post-layout.css']
subprocess.run(['git','reset','--soft',latest],check=True)
subprocess.run(['git','add','--all'],check=True)
tree=subprocess.check_output(['git','write-tree'],text=True).strip()
assert tree=='b5f8379f44685ff2c6771222c073029f35851212',tree
print('Verified complete current-source bundle and all generated bytes:',tree,versions)
